name: myenv

channels:
  - conda-forge  # Canal recomendado para la mayoría de las librerías
  - defaults  # Canal por defecto de conda

dependencies:
  - python=3.10.13  # Versión de Python
  - pyautogui==0.9.54
  - pillow==11.1.0
  - tkcap
  - pydicom==3.0.1
  - img2pdf==0.5.1
  - opencv-python>=4.1,<4.2
  - matplotlib==3.10.0
  - pandas==2.2.3
  - tensorflow==2.10.0
  - python-xlib==0.33

# Si necesitas instalar paquetes desde pip
# pip:
#   - nombre_del_paquete